<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">เมนูหลัก</li>
            <li><a href="#"><i class="fa fa-book"></i> <span>ข้อมูลวิชาและชั้นเรียน</span></a></li>
            <li><a href="#"><i class="fa fa-book"></i> <span>เพิ่มวิชา</span></a></li>
            <li><a href="#"><i class="fa fa-printer"></i> <span>พิมพ์รายงาน</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>
